# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b76b5fa27469f38ec6d369a771ddda363629de3ee03d6e5c5cb9de2e36693438e1ed3d09f53b698abb508f250603943c21d05f4e786ab24f8f8d5b47d82423f7

test:
  secret_key_base: 01345b63bf5bc0977cfbd5ec9a83c735c26f4d4ef49b7ca61632eb561e6a1b2e9f9f461e07f43b686943d9f6c461642694336750e915dc9d23ad15829a71b730

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
